export const ROUTES = {
	AUTH: {
		BASE: "/auth",
		LOGIN: "/login",
		REGISTER: "/register",
		VERIFY_REGISTER_OTP: "/verify-registration-otp",
		RESEND_REGISTER_OTP: "/resend-registration-otp",
		GOOGLE: "/google",
		LINKEDIN: "/linkedin",
		SAVE_INTERESTS: "/save-interests",
		REQUEST_PASSWORD_RESET: "/reset-password",
		VERIFY_RESET_PASSWORD_OTP: "/verify-reset-password-otp",
		RESEND_RESET_PASSWORD_OTP: "/resend-reset-password-otp",
		UPDATE_PASSWORD: "/update-password",
		REFRESH: "/refresh",
		LOGOUT: "/logout",
		REVOKE_SESSION: "/revoke-session",
		REVOKE_ALL_OTHER_SESSIONS: "/revoke-all-other-sessions",
		ACTIVE_SESSIONS: "/active-sessions",
	},
	PROFILE: {
		BASE: "/profile",
		ME: "/me",
		ROOT: "/",
		CHANGE_PASSWORD: "/change-password",
		REQUEST_CHANGE_PASSWORD: "/change-password/request",
		VERIFY_OTP: "/change-password/verify",
	},
	CATALOG: {
		BASE: "/catalog",
		ONBOARDING: "/onboarding",
		PROFESSIONS: "/professions",
		FETCH: "/fetch",
	},
	USER_MANAGEMENT: {
		BASE: "/user-management",
		FETCH_USERS: "/fetch-users",
		BLOCK: (id: string) => `/${id}/block`,
		UNBLOCK: (id: string) => `/${id}/unblock`,
	},
	STORAGE: {
		BASE: "/storage",
		GET_PRESIGNED_URL: "/presigned-upload-url",
		DELETE: "/delete",
	},
	MENTOR: {
		BASE: "/mentor",
		REGISTRATION_INFO: "/registration-info",
		REGISTER: "/register",
		RESUBMIT: "/resubmit",
		APPLICATIONS: "/applications",
		APPROVE: (id: string) => `/applications/${id}/approve`,
		REJECT: (id: string) => `/applications/${id}/reject`,
	},
};
