export const ROUTES = {
	AUTH: {
		BASE: "/auth",
		LOGIN: "/login",
		REGISTER: "/register",
		VERIFY_REGISTER_OTP: "/verify-registration-otp",
		RESEND_REGISTER_OTP: "/resend-registration-otp",
		GOOGLE: "/google",
		LINKEDIN: "/linkedin",
		SAVE_INTERESTS: "/save-interests",
		REQUEST_PASSWORD_RESET: "/reset-password",
		VERIFY_RESET_PASSWORD_OTP: "/verify-reset-password-otp",
		RESEND_RESET_PASSWORD_OTP: "/resend-reset-password-otp",
		UPDATE_PASSWORD: "/update-password",
		REFRESH: "/refresh",
		LOGOUT: "/logout",
		REVOKE_SESSION: "/revoke-session",
		REVOKE_ALL_OTHER_SESSIONS: "/revoke-all-other-sessions",
		ACTIVE_SESSIONS: "/active-sessions",
	},
	PROFILE: {
		BASE: "/profile",
		ME: "/me",
		ROOT: "/",
		CHANGE_PASSWORD: "/change-password",
		REQUEST_CHANGE_PASSWORD: "/change-password/request",
		VERIFY_OTP: "/change-password/verify",
	},
	CATALOG: {
		BASE: "/catalog",
		ONBOARDING: "/onboarding",
		PROFESSIONS: "/professions",
		FETCH: "/fetch",
		ADD_INTEREST: "/interests",
		DISABLE_INTEREST: (id: string) => `/interests/${id}/disable`,
		ENABLE_INTEREST: (id: string) => `/interests/${id}/enable`,
		ADD_SKILL: "/skills",
		DISABLE_SKILL: (id: string) => `/skills/${id}/disable`,
		ENABLE_SKILL: (id: string) => `/skills/${id}/enable`,
		ADD_PROFESSION: "/professions",
		DISABLE_PROFESSION: (id: string) => `/professions/${id}/disable`,
		ENABLE_PROFESSION: (id: string) => `/professions/${id}/enable`,
	},
	USER_MANAGEMENT: {
		BASE: "/user-management",
		FETCH_USERS: "/fetch-users",
		BLOCK: (id: string) => `/${id}/block`,
		UNBLOCK: (id: string) => `/${id}/unblock`,
	},
	ADMIN_MANAGEMENT: {
		BASE: "/admin-management",
		FETCH_ADMINS: "/fetch-admins",
		CREATE_ADMIN: "/create",
		BLOCK: (id: string) => `/${id}/block`,
		UNBLOCK: (id: string) => `/${id}/unblock`,
	},
	STORAGE: {
		BASE: "/storage",
		GET_PRESIGNED_URL: "/presigned-upload-url",
		DELETE: "/delete",
	},
	MENTOR: {
		BASE: "/mentor",
		REGISTRATION_INFO: "/registration-info",
		REGISTER: "/register",
		RESUBMIT: "/resubmit",
		DISCOVERY: "/discover",
		APPLICATIONS: "/applications",
		APPROVE: (id: string) => `/applications/${id}/approve`,
		REJECT: (id: string) => `/applications/${id}/reject`,
	},
	MENTOR_LISTS: {
		BASE: "/mentor-lists",
		ROOT: "/",
		BY_ID: "/:listId",
		ADD_MENTOR: "/:listId/mentors",
		REMOVE_MENTOR: "/:listId/mentors/:mentorId",
	},
	RECURRING_RULES: {
		BASE: "/recurring-rules",
		ROOT: "/",
		BY_ID: "/:ruleId",
		ENABLE: (ruleId: string) => `/${ruleId}/enable`,
		DISABLE: (ruleId: string) => `/${ruleId}/disable`,
	},
	PLATFORM_SETTINGS: {
		BASE: "/platform-settings",
		FETCH: "/fetch",
		ECONOMY: "/economy",
		MENTORS: "/mentors",
		CONTENT: "/content",
		SESSIONS: "/sessions",
	},
	PAYMENTS: {
		BASE: "/payments",
		CHECKOUT_SESSION: "/checkout-session",
		WEBHOOK: "/webhook",
	},
	WALLET: {
		BASE: "/wallet",
		COIN_BALANCE: "/balance",
		COIN_TRANSACTIONS: "/coin-transactions",
		PAYMENT_TRANSACTIONS: "/payment-transactions",
	},
};
