export * from "./approveMentor.uc.interface";
export * from "./fechMentorByExpertise.uc.interface";
export * from "./fetchMentorDetails.uc.interface";
export * from "./fetchMentors.uc.interface";
export * from "./fetchSelf.uc.interface";
export * from "./findMentorByExpertiseandSkill.uc.interface";
export * from "./registerAsMentor.uc.interface";
export * from "./rejectMentor.uc.interface";
export * from "./updateMentor.uc.interface";
