export enum NotificationPayloadTypes {
	REACT_ARTICLE = "REACT_ARTICLE",
	REACT_COMMENT = "REACT_COMMENT",
	COMMENT_ARTICLE = "COMMENT_ARTICLE",
	REPLY_COMMENT = "REPLY_COMMENT",
	RECIEVED_MESSAGE = "RECIEVED_MESSAGE",
	BOOKED_SESSION = "BOOKED_SESSION",
	CONFIRMED_SESSION = "CONFIRMED_SESSION",
	CANCELLED_SESSION = "CANCELLED_SESSION",
	SESSION_REMINDER = "SESSION_REMINDER",
	SESSION_COMMENCE_REMINDER = "SESSION_COMMENCE_REMINDER",
	USER_FOLLOWED = "USER_FOLLOWED",
}
