import type { Container } from "inversify";
import type {
	IArticleCommentRepository,
	IArticleReactionRepository,
	IArticleRepository,
	IArticleViewRepository,
	IChatMessageRepository,
	IChatRepository,
	IMentorListReadRepository,
	IMentorListRepository,
	IMentorProfileReadRepository,
	IMentorWriteRepository,
	INotificationRepository,
	IPlatformSettingsRepository,
	IProfessionRepository,
	ISavedMentorRepository,
} from "../../domain/repositories";
import {
	MongoArticleCommentRepository,
	MongoArticleReactionRepository,
	MongoArticleRepository,
	MongoArticleViewRepository,
	MongoChatMessageRepository,
	MongoChatRepository,
	MongoCoinTransactionRepository,
	MongoInterestRepository,
	MongoMentorListReadRepository,
	MongoMentorListRepository,
	MongoMentorProfileReadRepository,
	MongoMentorWriteRepository,
	MongoNotificationRepository,
	MongoPaymentTransactionRepository,
	MongoPlatformSettingsRepository,
	MongoPlatformWalletRepository,
	MongoSavedMentorRepository,
	MongoSessionAvailabilityRepository,
	MongoSessionBookingRepository,
	MongoSessionRepository,
	MongoSessionSlotRepository,
	MongoSkillRepository,
	MongoUserRepository,
} from "../../infrastructure/database/mongodb/repositories";
import { MongoProfessionRepository } from "../../infrastructure/database/mongodb/repositories/profession.repository";
import { RedisOtpRepository } from "../../infrastructure/database/redis/repositories/otp.repository";
import { RedisTokenRevocationRepository } from "../../infrastructure/database/redis/repositories/token-revocation.repository";
import { TYPES } from "../../shared/types/types";

export const registerRepositoryBindings = (container: Container): void => {
	container
		.bind(TYPES.Repositories.UserRepository)
		.to(MongoUserRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.CoinTransactionRepository)
		.to(MongoCoinTransactionRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.OtpRepository)
		.to(RedisOtpRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.PaymentTransactionRepository)
		.to(MongoPaymentTransactionRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.PlatformWalletRepository)
		.to(MongoPlatformWalletRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.SessionRepository)
		.to(MongoSessionRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.TokenRevocationRepository)
		.to(RedisTokenRevocationRepository)
		.inSingletonScope();
	container
		.bind<IPlatformSettingsRepository>(
			TYPES.Repositories.PlatformSettingsRepository,
		)
		.to(MongoPlatformSettingsRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.InterestRepository)
		.to(MongoInterestRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.SkillRepository)
		.to(MongoSkillRepository)
		.inSingletonScope();
	container
		.bind<IProfessionRepository>(TYPES.Repositories.ProfessionRepository)
		.to(MongoProfessionRepository)
		.inSingletonScope();
	container
		.bind<IMentorWriteRepository>(TYPES.Repositories.MentorWriteRepository)
		.to(MongoMentorWriteRepository)
		.inSingletonScope();
	container
		.bind<IMentorProfileReadRepository>(
			TYPES.Repositories.MentorProfileReadRepository,
		)
		.to(MongoMentorProfileReadRepository)
		.inSingletonScope();
	container
		.bind<IMentorListReadRepository>(
			TYPES.Repositories.MentorListReadRepository,
		)
		.to(MongoMentorListReadRepository)
		.inSingletonScope();
	container
		.bind<IMentorListRepository>(TYPES.Repositories.MentorListRepository)
		.to(MongoMentorListRepository)
		.inSingletonScope();
	container
		.bind<IChatRepository>(TYPES.Repositories.ChatRepository)
		.to(MongoChatRepository)
		.inSingletonScope();
	container
		.bind<IChatMessageRepository>(TYPES.Repositories.ChatMessageRepository)
		.to(MongoChatMessageRepository)
		.inSingletonScope();
	container
		.bind<INotificationRepository>(TYPES.Repositories.NotificationRepository)
		.to(MongoNotificationRepository)
		.inSingletonScope();
	container
		.bind<IArticleRepository>(TYPES.Repositories.ArticleRepository)
		.to(MongoArticleRepository)
		.inSingletonScope();
	container
		.bind<IArticleCommentRepository>(
			TYPES.Repositories.ArticleCommentRepository,
		)
		.to(MongoArticleCommentRepository)
		.inSingletonScope();
	container
		.bind<IArticleReactionRepository>(
			TYPES.Repositories.ArticleReactionRepository,
		)
		.to(MongoArticleReactionRepository)
		.inSingletonScope();
	container
		.bind<IArticleViewRepository>(TYPES.Repositories.ArticleViewRepository)
		.to(MongoArticleViewRepository)
		.inSingletonScope();
	container
		.bind<ISavedMentorRepository>(TYPES.Repositories.SavedMentorRepository)
		.to(MongoSavedMentorRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.SessionAvailabilityRepository)
		.to(MongoSessionAvailabilityRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.SessionSlotRepository)
		.to(MongoSessionSlotRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.SessionBookingRepository)
		.to(MongoSessionBookingRepository)
		.inSingletonScope();
};
