import type { Container } from "inversify";
import type {
	IAdminDashboardRepository,
	IArticleCommentRepository,
	IArticleReactionRepository,
	IArticleRepository,
	IArticleViewRepository,
	IAvailabilityRepository,
	IBookingRepository,
	IChatMessageRepository,
	IChatRepository,
	IDashboardRepository,
	IMentorListReadRepository,
	IMentorListRepository,
	IMentorProfileReadRepository,
	IMentorWriteRepository,
	INotificationRepository,
	IProfessionRepository,
	IPushSubscriptionRepository,
	IReportRepository,
	IReviewRepository,
	ISavedMentorRepository,
} from "../../domain/repositories";

import {
	AvailabilityRepository,
	BookingRepository,
	MongoAdminDashboardRepository,
	MongoArticleCommentRepository,
	MongoArticleReactionRepository,
	MongoArticleRepository,
	MongoArticleViewRepository,
	MongoChatMessageRepository,
	MongoChatRepository,
	MongoCoinTransactionRepository,
	MongoDashboardRepository,
	MongoInterestRepository,
	MongoMentorListReadRepository,
	MongoMentorListRepository,
	MongoMentorProfileReadRepository,
	MongoMentorWriteRepository,
	MongoNotificationRepository,
	MongoosePushSubscriptionRepository,
	MongoPaymentTransactionRepository,
	MongoPlatformWalletRepository,
	MongoReportRepository,
	MongoReviewRepository,
	MongoSavedMentorRepository,
	MongoSessionRepository,
	MongoSkillRepository,
	MongoUserRepository,
} from "../../infrastructure/database/mongodb/repositories";

import { MongoProfessionRepository } from "../../infrastructure/database/mongodb/repositories/profession.repository";
import { RedisOtpRepository } from "../../infrastructure/database/redis/repositories/otp.repository";
import { RedisTokenRevocationRepository } from "../../infrastructure/database/redis/repositories/token-revocation.repository";
import { TYPES } from "../../shared/types/types";

export const registerRepositoryBindings = (container: Container): void => {
	container
		.bind<IAdminDashboardRepository>(
			TYPES.Repositories.AdminDashboardRepository,
		)
		.to(MongoAdminDashboardRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.UserRepository)
		.to(MongoUserRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.CoinTransactionRepository)
		.to(MongoCoinTransactionRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.OtpRepository)
		.to(RedisOtpRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.PaymentTransactionRepository)
		.to(MongoPaymentTransactionRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.PlatformWalletRepository)
		.to(MongoPlatformWalletRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.SessionRepository)
		.to(MongoSessionRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.TokenRevocationRepository)
		.to(RedisTokenRevocationRepository)
		.inSingletonScope();

	container
		.bind(TYPES.Repositories.InterestRepository)
		.to(MongoInterestRepository)
		.inSingletonScope();
	container
		.bind(TYPES.Repositories.SkillRepository)
		.to(MongoSkillRepository)
		.inSingletonScope();
	container
		.bind<IProfessionRepository>(TYPES.Repositories.ProfessionRepository)
		.to(MongoProfessionRepository)
		.inSingletonScope();

	container
		.bind<IMentorWriteRepository>(TYPES.Repositories.MentorWriteRepository)
		.to(MongoMentorWriteRepository)
		.inSingletonScope();
	container
		.bind<IMentorProfileReadRepository>(
			TYPES.Repositories.MentorProfileReadRepository,
		)
		.to(MongoMentorProfileReadRepository)
		.inSingletonScope();
	container
		.bind<IMentorListReadRepository>(
			TYPES.Repositories.MentorListReadRepository,
		)
		.to(MongoMentorListReadRepository)
		.inSingletonScope();
	container
		.bind<IMentorListRepository>(TYPES.Repositories.MentorListRepository)
		.to(MongoMentorListRepository)
		.inSingletonScope();
	container
		.bind<IChatRepository>(TYPES.Repositories.ChatRepository)
		.to(MongoChatRepository)
		.inSingletonScope();
	container
		.bind<IChatMessageRepository>(TYPES.Repositories.ChatMessageRepository)
		.to(MongoChatMessageRepository)
		.inSingletonScope();
	container
		.bind<INotificationRepository>(TYPES.Repositories.NotificationRepository)
		.to(MongoNotificationRepository)
		.inSingletonScope();
	container
		.bind<IReportRepository>(TYPES.Repositories.ReportRepository)
		.to(MongoReportRepository)
		.inSingletonScope();
	container
		.bind<IArticleRepository>(TYPES.Repositories.ArticleRepository)
		.to(MongoArticleRepository)
		.inSingletonScope();
	container
		.bind<IArticleCommentRepository>(
			TYPES.Repositories.ArticleCommentRepository,
		)
		.to(MongoArticleCommentRepository)
		.inSingletonScope();
	container
		.bind<IArticleReactionRepository>(
			TYPES.Repositories.ArticleReactionRepository,
		)
		.to(MongoArticleReactionRepository)
		.inSingletonScope();
	container
		.bind<IArticleViewRepository>(TYPES.Repositories.ArticleViewRepository)
		.to(MongoArticleViewRepository)
		.inSingletonScope();
	container
		.bind<ISavedMentorRepository>(TYPES.Repositories.SavedMentorRepository)
		.to(MongoSavedMentorRepository)
		.inSingletonScope();
	container
		.bind<IDashboardRepository>(TYPES.Repositories.DashboardRepository)
		.to(MongoDashboardRepository)
		.inSingletonScope();
	container
		.bind<IAvailabilityRepository>(TYPES.Repositories.AvailabilityRepository)
		.to(AvailabilityRepository)
		.inSingletonScope();
	container
		.bind<IBookingRepository>(TYPES.Repositories.BookingRepository)
		.to(BookingRepository)
		.inSingletonScope();
	container
		.bind<IReviewRepository>(TYPES.Repositories.ReviewRepository)
		.to(MongoReviewRepository)
		.inSingletonScope();
	container
		.bind<IPushSubscriptionRepository>(
			TYPES.Repositories.PushSubscriptionRepository,
		)
		.to(MongoosePushSubscriptionRepository)
		.inSingletonScope();
};
