export * from "./admin-management.route";
export { default as adminManagementRouter } from "./admin-management.route";
export * from "./auth.route";
export * from "./catalog.route";
export * from "./file.route";
export * from "./mentor.route";
export * from "./mentor-list.route";
export * from "./payment.route";
export * from "./platform-settings.route";
export * from "./profile.route";
export * from "./user-management.route";
export { default as userManagementRouter } from "./user-management.route";
export * from "./v1.route";
export * from "./wallet.route";
