export const TYPES = {
	Services: {
		Password: Symbol.for("Password"),
		TokenService: Symbol.for("TokenService"),
		MailService: Symbol.for("MailService"),
		JobQueue: Symbol.for("JobQueuePort"),
		BookingJobQueue: Symbol.for("BookingJobQueuePort"),
		OtpGenerator: Symbol.for("OtpGenerator"),
		GoogleOAuth: Symbol.for("GoogleOAuth"),
		LinkedInOAuth: Symbol.for("LinkedInOAuth"),
		AuthSession: Symbol.for("AuthSession"),
		Storage: Symbol.for("Storage"),
		WalletService: Symbol.for("WalletService"),
		EventBus: Symbol.for("EventBus"),
		NotificationPort: Symbol.for("NotificationPort"),
		PushNotificationPort: Symbol.for("PushNotificationPort"),
		PaymentService: Symbol.for("PaymentService"),
		PaymentWebhookParser: Symbol.for("PaymentWebhookParser"),
		IdGenerator: Symbol.for("IdGenerator"),
		RefundService: Symbol.for("RefundService"),
		ConfirmBookingPaymentService: Symbol.for("ConfirmBookingPaymentService"),
		ProcessWalletTopupService: Symbol.for("ProcessWalletTopupService"),
		UpsertPaymentTransactionService: Symbol.for(
			"UpsertPaymentTransactionService",
		),
		SessionSettlementCalculator: Symbol.for("SessionSettlementCalculator"),
		MentorSessionPayout: Symbol.for("MentorSessionPayout"),
		SessionRefund: Symbol.for("SessionRefund"),
		MentorNoShow: Symbol.for("MentorNoShow"),
		WebSocketServer: Symbol.for("WebSocketServer"),
		PdfReceiptService: Symbol.for("PdfReceiptService"),
		FeedCacheService: Symbol.for("FeedCacheService"),
	},
	WebSockets: {
		CallHandler: Symbol.for("CallHandler"),
	},
	Caches: {
		Whiteboard: Symbol.for("WhiteboardCache"),
	},
	Queues: {
		NotificationQueue: Symbol.for("NotificationQueue"),
		BookingSettlementQueue: Symbol.for("BookingSettlementQueue"),
	},
	Workers: {
		NotificationWorkerFactory: Symbol.for("NotificationWorkerFactory"),
		BookingWorkerFactory: Symbol.for("BookingWorkerFactory"),
		RegisterOtpHandler: Symbol.for("RegisterOtpHandler"),
		ResetPasswordOtpHandler: Symbol.for("ResetPasswordOtpHandler"),
		ChangePasswordOtpHandler: Symbol.for("ChangePasswordOtpHandler"),
		MentorApprovalHandler: Symbol.for("MentorApprovalHandler"),
		SessionReminderHandler: Symbol.for("SessionReminderHandler"),
		BookingSettlementHandler: Symbol.for("BookingSettlementHandler"),
	},
	Repositories: {
		AdminDashboardRepository: Symbol.for("AdminDashboardRepository"),
		UserRepository: Symbol.for("UserRepository"),
		CoinTransactionRepository: Symbol.for("CoinTransactionRepository"),
		OtpRepository: Symbol.for("OtpRepository"),
		PaymentTransactionRepository: Symbol.for("PaymentTransactionRepository"),
		PlatformWalletRepository: Symbol.for("PlatformWalletRepository"),
		SessionRepository: Symbol.for("SessionRepository"),
		TokenRevocationRepository: Symbol.for("TokenRevocationRepository"),
		InterestRepository: Symbol.for("InterestRepository"),
		SkillRepository: Symbol.for("SkillRepository"),
		MentorWriteRepository: Symbol.for("MentorWriteRepository"),
		MentorProfileReadRepository: Symbol.for("MentorProfileReadRepository"),
		MentorListReadRepository: Symbol.for("MentorListReadRepository"),
		ProfessionRepository: Symbol.for("ProfessionRepository"),
		MentorListRepository: Symbol.for("MentorListRepository"),
		ChatRepository: Symbol.for("ChatRepository"),
		ChatMessageRepository: Symbol.for("ChatMessageRepository"),
		NotificationRepository: Symbol.for("NotificationRepository"),
		ReportRepository: Symbol.for("ReportRepository"),
		ArticleRepository: Symbol.for("ArticleRepository"),
		ArticleCommentRepository: Symbol.for("ArticleCommentRepository"),
		ArticleReactionRepository: Symbol.for("ArticleReactionRepository"),
		ArticleViewRepository: Symbol.for("ArticleViewRepository"),
		SavedMentorRepository: Symbol.for("SavedMentorRepository"),
		DashboardRepository: Symbol.for("DashboardRepository"),
		AvailabilityRepository: Symbol.for("AvailabilityRepository"),
		BookingRepository: Symbol.for("BookingRepository"),
		ReviewRepository: Symbol.for("ReviewRepository"),
		PushSubscriptionRepository: Symbol.for("PushSubscriptionRepository"),
	},

	Databases: {
		Redis: Symbol.for("Redis"),
	},
	UseCases: {
		LoginWithEmail: Symbol.for("LoginWithEmailUseCase"),
		SocialLogin: Symbol.for("SocialLoginUseCase"),
		RequestPasswordReset: Symbol.for("RequestPasswordResetUseCase"),
		RegisterWithEmail: Symbol.for("RegisterWithEmailUseCase"),
		VerifyRegistrationOtp: Symbol.for("VerifyRegistrationOtpUseCase"),
		VerifyResetPasswordOtp: Symbol.for("VerifyResetPasswordOtpUseCase"),
		VerifyChangePasswordOtp: Symbol.for("VerifyChangePasswordOtpUseCase"),
		ResendRegistrationOtp: Symbol.for("ResendRegistrationOtpUseCase"),
		ResendResetPasswordOtp: Symbol.for("ResendResetPasswordOtpUseCase"),
		ChangePassword: Symbol.for("ChangePasswordUseCase"),
		RequestChangePassword: Symbol.for("RequestChangePasswordUseCase"),
		UpdatePassword: Symbol.for("UpdatePasswordUseCase"),
		RefreshSession: Symbol.for("RefreshSessionUseCase"),
		Logout: Symbol.for("LogoutUseCase"),
		RevokeSession: Symbol.for("RevokeSessionUseCase"),
		RevokeAllOtherSessions: Symbol.for("RevokeAllOtherSessionsUseCase"),
		SaveUserInterests: Symbol.for("SaveUserInterestsUseCase"),
		RegisterPushSubscription: Symbol.for("RegisterPushSubscriptionUseCase"),
		UnregisterPushSubscription: Symbol.for("UnregisterPushSubscriptionUseCase"),
		CreateNotification: Symbol.for("CreateNotificationUseCase"),
		GetNotifications: Symbol.for("GetNotificationsUseCase"),
		MarkNotificationRead: Symbol.for("MarkNotificationReadUseCase"),
		MarkAllNotificationsRead: Symbol.for("MarkAllNotificationsReadUseCase"),
		GetUnreadNotificationCount: Symbol.for("GetUnreadNotificationCountUseCase"),
		GetChats: Symbol.for("GetChatsUseCase"),
		GetChat: Symbol.for("GetChatUseCase"),
		CreateChat: Symbol.for("CreateChatUseCase"),
		SendChatMessage: Symbol.for("SendChatMessageUseCase"),
		MarkChatMessagesRead: Symbol.for("MarkChatMessagesReadUseCase"),
		AddInterest: Symbol.for("AddInterestUseCase"),
		AddSkill: Symbol.for("AddSkillUseCase"),
		AddProfession: Symbol.for("AddProfessionUseCase"),
		FetchCatalog: Symbol.for("FetchCatalogUseCase"),
		DisableSkill: Symbol.for("DisableSkillUseCase"),
		DisableInterest: Symbol.for("DisableInterestUseCase"),
		DisableProfession: Symbol.for("DisableProfessionUseCase"),
		EnableSkill: Symbol.for("EnableSkillUseCase"),
		EnableInterest: Symbol.for("EnableInterestUseCase"),
		EnableProfession: Symbol.for("EnableProfessionUseCase"),
		GetOnboardingCatalog: Symbol.for("GetOnboardingCatalog"),
		GetProfessions: Symbol.for("GetProfessions"),
		GetMe: Symbol.for("GetMeUseCase"),
		GetActiveSessions: Symbol.for("GetActiveSessionsUseCase"),
		GetUsers: Symbol.for("GetUsersUseCase"),
		BlockUser: Symbol.for("BlockUserUseCase"),
		UnblockUser: Symbol.for("UnblockUserUseCase"),
		GetAdmins: Symbol.for("GetAdminsUseCase"),
		CreateAdmin: Symbol.for("CreateAdminUseCase"),
		BlockAdmin: Symbol.for("BlockAdminUseCase"),
		UnblockAdmin: Symbol.for("UnblockAdminUseCase"),
		GetPreSignedUploadUrl: Symbol.for("GetPreSignedUploadUrlUseCase"),
		GetPreSignedDownloadUrl: Symbol.for("GetPreSignedDownloadUrlUseCase"),
		DeleteFile: Symbol.for("DeleteFileUseCase"),
		GetMentorRegistrationInfo: Symbol.for("GetMentorRegistrationInfoUseCase"),
		GetMentorProfile: Symbol.for("GetMentorProfileUseCase"),
		GetPublicMentorProfile: Symbol.for("GetPublicMentorProfileUseCase"),
		UpdateMentorProfile: Symbol.for("UpdateMentorProfileUseCase"),
		RegisterMentor: Symbol.for("RegisterMentorUseCase"),
		ResubmitMentor: Symbol.for("ResubmitMentorUseCase"),
		GetMentorApplications: Symbol.for("GetMentorApplicationsUseCase"),
		ApproveMentor: Symbol.for("ApproveMentorUseCase"),
		RejectMentor: Symbol.for("RejectMentorUseCase"),
		UpdateEconomySettings: Symbol.for("UpdateEconomySettingsUseCase"),
		UpdateMentorSettings: Symbol.for("UpdateMentorSettingsUseCase"),
		UpdateContentSettings: Symbol.for("UpdateContentSettingsUseCase"),
		UpdateSessionSettings: Symbol.for("UpdateSessionSettingsUseCase"),
		GetProfile: Symbol.for("GetProfileUseCase"),
		UpdateProfile: Symbol.for("UpdateProfileUseCase"),
		GetMentorLists: Symbol.for("GetMentorListsUseCase"),
		GetMentorList: Symbol.for("GetMentorListUseCase"),
		CreateMentorList: Symbol.for("CreateMentorListUseCase"),
		AddMentorToList: Symbol.for("AddMentorToListUseCase"),
		RemoveMentorFromList: Symbol.for("RemoveMentorFromListUseCase"),
		DeleteMentorList: Symbol.for("DeleteMentorListUseCase"),
		GetMentorsDiscovery: Symbol.for("GetMentorsDiscoveryUseCase"),
		CreateArticle: Symbol.for("CreateArticleUseCase"),
		UpdateArticle: Symbol.for("UpdateArticleUseCase"),
		DeleteArticle: Symbol.for("DeleteArticleUseCase"),
		BlockArticle: Symbol.for("BlockArticleUseCase"),
		UnblockArticle: Symbol.for("UnblockArticleUseCase"),
		SubmitArticleAppeal: Symbol.for("SubmitArticleAppealUseCase"),
		GetArticle: Symbol.for("GetArticleUseCase"),
		GetArticles: Symbol.for("GetArticlesUseCase"),
		GetArticleTopTags: Symbol.for("GetArticleTopTagsUseCase"),
		MarkArticleView: Symbol.for("MarkArticleViewUseCase"),
		CreateArticleComment: Symbol.for("CreateArticleCommentUseCase"),
		UpdateArticleComment: Symbol.for("UpdateArticleCommentUseCase"),
		DeleteArticleComment: Symbol.for("DeleteArticleCommentUseCase"),
		GetArticleComments: Symbol.for("GetArticleCommentsUseCase"),
		ReactToArticle: Symbol.for("ReactToArticleUseCase"),
		ReactToArticleComment: Symbol.for("ReactToArticleCommentUseCase"),
		ReportArticle: Symbol.for("ReportArticleUseCase"),
		ReportUser: Symbol.for("ReportUserUseCase"),
		GetReports: Symbol.for("GetReportsUseCase"),
		UpdateReportStatus: Symbol.for("UpdateReportStatusUseCase"),
		// Availability
		CreateAvailability: Symbol.for("CreateAvailabilityUseCase"),
		CheckAndCreateAvailability: Symbol.for("CheckAndCreateAvailabilityUseCase"),
		CheckAndReenableAvailability: Symbol.for(
			"CheckAndReenableAvailabilityUseCase",
		),
		UpdateAvailability: Symbol.for("UpdateAvailabilityUseCase"),
		DeleteAvailability: Symbol.for("DeleteAvailabilityUseCase"),
		ReenableAvailability: Symbol.for("ReenableAvailabilityUseCase"),
		GetMentorAvailabilities: Symbol.for("GetMentorAvailabilitiesUseCase"),

		// Bookings
		GetAvailableSlots: Symbol.for("GetAvailableSlotsUseCase"),
		CreateBooking: Symbol.for("CreateBookingUseCase"),
		CancelBooking: Symbol.for("CancelBookingUseCase"),
		CancelBookingByMentor: Symbol.for("CancelBookingByMentorUseCase"),
		RefundSessionAmount: Symbol.for("RefundSessionAmountUseCase"),
		GetBookingDetails: Symbol.for("GetBookingDetailsUseCase"),
		GetUserBookings: Symbol.for("GetUserBookingsUseCase"),
		GetMentorBookings: Symbol.for("GetMentorBookingsUseCase"),
		RepayBooking: Symbol.for("RepayBookingUseCase"),
		GenerateReceiptPdf: Symbol.for("GenerateReceiptPdfUseCase"),
		ScheduleSessionSettlement: Symbol.for("ScheduleSessionSettlementUseCase"),
		SettleEndedSession: Symbol.for("SettleEndedSessionUseCase"),
		CreateReview: Symbol.for("CreateReviewUseCase"),
		GetMentorReviews: Symbol.for("GetMentorReviewsUseCase"),
		GetDashboard: Symbol.for("GetDashboardUseCase"),
		GetDashboardActivityOverview: Symbol.for(
			"GetDashboardActivityOverviewUseCase",
		),
		GetAdminDashboard: Symbol.for("GetAdminDashboardUseCase"),
		GetAdminDashboardUserGrowth: Symbol.for(
			"GetAdminDashboardUserGrowthUseCase",
		),
		GetAdminDashboardRevenueAnalytics: Symbol.for(
			"GetAdminDashboardRevenueAnalyticsUseCase",
		),
		GetAdminDashboardSessionOverview: Symbol.for(
			"GetAdminDashboardSessionOverviewUseCase",
		),

		CreateCheckoutSession: Symbol.for("CreateCheckoutSessionUseCase"),
		HandlePaymentWebhook: Symbol.for("HandlePaymentWebhookUseCase"),
		ProcessPaymentEvent: Symbol.for("ProcessPaymentEventUseCase"),
		GetCoinBalance: Symbol.for("GetCoinBalanceUseCase"),
		GetCoinTransactions: Symbol.for("GetCoinTransactionsUseCase"),
		GetPaymentTransactions: Symbol.for("GetPaymentTransactionsUseCase"),
		GetPlatformWallet: Symbol.for("GetPlatformWalletUseCase"),
		GetPlatformCoinTransactions: Symbol.for(
			"GetPlatformCoinTransactionsUseCase",
		),
		GetPlatformPaymentTransactions: Symbol.for(
			"GetPlatformPaymentTransactionsUseCase",
		),
		JoinSession: Symbol.for("JoinSessionUseCase"),
		TerminateSession: Symbol.for("TerminateSessionUseCase"),
		AuthorizeWhiteboardPermission: Symbol.for(
			"AuthorizeWhiteboardPermissionUseCase",
		),
		ValidateJoinSession: Symbol.for("ValidateJoinSessionUseCase"),
		ScheduleLiveSesionReminder: Symbol.for("ScheduleLiveSesionReminderUseCase"),
		UpdateSkill: Symbol.for("UpdateSkillUseCase"),
		UpdateProfession: Symbol.for("UpdateProfessionUseCase"),
		UpdateInterest: Symbol.for("UpdateInterestUseCase"),
	},
	Controllers: {
		Users: Symbol.for("UserController"),
		Admins: Symbol.for("AdminsController"),
		Authentication: Symbol.for("AuthenticationController"),
		Article: Symbol.for("ArticleController"),
		Skill: Symbol.for("SkillController"),
		Catalog: Symbol.for("CatalogController"),
		System: Symbol.for("SystemController"),
		Mentor: Symbol.for("MentorController"),
		Profile: Symbol.for("ProfileController"),
		File: Symbol.for("FileController"),
		MentorList: Symbol.for("MentorListController"),
		Chat: Symbol.for("ChatController"),
		Notification: Symbol.for("NotificationController"),
		Payment: Symbol.for("PaymentController"),
		Wallet: Symbol.for("WalletController"),
		Report: Symbol.for("ReportController"),

		Availability: Symbol.for("AvailabilityController"),
		Booking: Symbol.for("BookingController"),
		Review: Symbol.for("ReviewController"),
		Dashboard: Symbol.for("DashboardController"),
		AdminDashboard: Symbol.for("AdminDashboardController"),
	},
	PaymentHandlers: {
		CheckoutCompleted: Symbol.for("CheckoutCompletedHandler"),
		CheckoutExpired: Symbol.for("CheckoutExpiredHandler"),
		CheckoutFailed: Symbol.for("CheckoutFailedHandler"),
	},
};
