export const TYPES = {
	Services: {
		Hasher: Symbol.for("Hasher"),
		TokenService: Symbol.for("TokenService"),
		MailService: Symbol.for("MailService"),
		OtpGenerator: Symbol.for("OtpGenerator"),
		Storage: Symbol.for("Storage"),
	},
	Queues: {
		MailQueue: Symbol.for("MailQueue"),
	},
	Repositories: {
		UserRepository: Symbol.for("UserRepository"),
		OtpRepository: Symbol.for("OtpRepository"),
		SessionRepository: Symbol.for("SessionRepository"),
		TokenRevocationRepository: Symbol.for("TokenRevocationRepository"),
		InterestRepository: Symbol.for("InterestRepository"),
		SkillRepository: Symbol.for("SkillRepository"),
		MentorRepository: Symbol.for("MentorRepository"),
		ProfessionRepository: Symbol.for("ProfessionRepository"),
	},
	Databases: {
		Redis: Symbol.for("Redis"),
	},
	UseCases: {
		LoginWithEmail: Symbol.for("LoginWithEmailUseCase"),
		RequestPasswordReset: Symbol.for("RequestPasswordResetUseCase"),
		RegisterWithEmail: Symbol.for("RegisterWithEmailUseCase"),
		VerifyOtp: Symbol.for("VerifyOtpUseCase"),
		ResendOtp: Symbol.for("ResendOtpUseCase"),
		ChangePassword: Symbol.for("ChangePasswordUseCase"),
		RefreshSession: Symbol.for("RefreshSessionUseCase"),
		Logout: Symbol.for("LogoutUseCase"),
		RevokeSession: Symbol.for("RevokeSessionUseCase"),
		RevokeAllOtherSessions: Symbol.for("RevokeAllOtherSessionsUseCase"),
		SaveUserInterests: Symbol.for("SaveUserInterestsUseCase"),
		GetOnboardingCatalog: Symbol.for("GetOnboardingCatalog"),
		GetProfessions: Symbol.for("GetProfessions"),
		GetMe: Symbol.for("GetMeUseCase"),
		GetActiveSessions: Symbol.for("GetActiveSessionsUseCase"),
		GetUsers: Symbol.for("GetUsersUseCase"),
		BlockUser: Symbol.for("BlockUserUseCase"),
		UnblockUser: Symbol.for("UnblockUserUseCase"),
		GetPreSignedUploadUrl: Symbol.for("GetPreSignedUploadUrlUseCase"),
		GetPreSignedDownloadUrl: Symbol.for("GetPreSignedDownloadUrlUseCase"),
		DeleteFile: Symbol.for("DeleteFileUseCase"),
		GetMentorRegistrationInfo: Symbol.for("GetMentorRegistrationInfoUseCase"),
		RegisterMentor: Symbol.for("RegisterMentorUseCase"),
		ResubmitMentor: Symbol.for("ResubmitMentorUseCase"),
		GetMentorApplications: Symbol.for("GetMentorApplicationsUseCase"),
		ApproveMentor: Symbol.for("ApproveMentorUseCase"),
		RejectMentor: Symbol.for("RejectMentorUseCase"),
	},
	Controllers: {
		UserManagement: Symbol.for("UserManagementController"),
		File: Symbol.for("FileController"),
		Mentor: Symbol.for("MentorController"),
	},
};
