name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.28.2

      - uses: actions/setup-node@v4
        with:
          node-version: "25"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm biome check . --diagnostic-level=error
      - run: pnpm type-check
